version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: be_healthy2
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 78873483mmv
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
