# Generated by Django 4.2.2 on 2023-06-29 16:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'прием пищи',
                'verbose_name_plural': 'приемы пищи',
                'ordering': ('date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MealProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('гр.', 'гр.'), ('мл.', 'мл.'), ('шт.', 'шт.'), ('ст.', 'ст.'), ('ст. л.', 'ст. л.'), ('ч. л.', 'ч. л.')], default='гр.', verbose_name='Единица измерения')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_amount', to='diary.meal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.product')),
            ],
            options={
                'verbose_name': 'продукт приема пищи',
                'verbose_name_plural': 'продукты приема пищи',
                'ordering': ('quantity', 'product'),
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='products',
            field=models.ManyToManyField(related_name='meals', through='diary.MealProduct', to='recipes.product'),
        ),
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='mealproduct',
            constraint=models.UniqueConstraint(fields=('product', 'meal'), name='unique_meal_product'),
        ),
    ]
