# Generated by Django 4.2.2 on 2023-06-30 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата'),
        ),
    ]
