# Generated by Django 4.2.1 on 2023-06-02 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='images/users', verbose_name='Аватар')),
                ('age', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity', models.DecimalField(choices=[(1, 'Без учета физ. нагрузки'), (1.2, 'Сидячий образ жизни'), (1.375, 'Легкая активность (1-2 раза в неделю)'), (1.55, 'Умеренная активность (3-5 раз в неделю)'), (1.725, 'Высокая активность (более 5 раз в неделю)'), (1.9, 'Очень высокая активность (профессиональный спорт)')], decimal_places=3, default=1.0, max_digits=4)),
                ('goal', models.DecimalField(choices=[(1, 'Поддержание веса'), (1.2, 'Набор веса'), (0.8, 'Снижение веса')], decimal_places=1, default=1, max_digits=2)),
                ('sex', models.CharField(choices=[('F', 'Женский'), ('M', 'Мужской')], default='F', max_length=1)),
                ('role', models.CharField(choices=[('U', 'Обычный пользователь'), ('A', 'Администратор')], default='U', max_length=1)),
                ('calories', models.DecimalField(decimal_places=1, default=2000.0, max_digits=4)),
                ('proteins', models.DecimalField(decimal_places=1, default=90.0, max_digits=4)),
                ('fats', models.DecimalField(decimal_places=1, default=60.0, max_digits=4)),
                ('carbohydrates', models.DecimalField(decimal_places=1, default=250.0, max_digits=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
