# Generated by Django 4.2.1 on 2023-06-02 15:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity',
            field=models.DecimalField(choices=[(Decimal('1'), 'Без учета физ. нагрузки'), (Decimal('1.2'), 'Сидячий образ жизни'), (Decimal('1.375'), 'Легкая активность (1-2 раза в неделю)'), (Decimal('1.55'), 'Умеренная активность (3-5 раз в неделю)'), (Decimal('1.725'), 'Высокая активность (более 5 раз в неделю)'), (Decimal('1.9'), 'Очень высокая активность (профессиональный спорт)')], decimal_places=3, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calories',
            field=models.DecimalField(decimal_places=1, default=2000.0, max_digits=5),
        ),
    ]
